apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: testing-api
  name: testing-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testing-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testing-api
    spec:
      containers:
      - image: punyakon/testapi:${VERSION}
        name: testingapi
        resources: {}
